export class Weights {
  public static ADMISSION_ALBUMIN_WEIGHT_IN_STAGE = 10 ;
  public static ADMISSION_NURSE_NUTRITION_WEIGHT_IN_STAGE = 20;
  public static ADMISSION_DIETITION_NUTRITION_WEIGHT_IN_STAGE = 20;
  public static ADMISSION_PAIN_WEIGHT_IN_STAGE = 10;
  public static ADMISSION_NOTRON_WEIGHT_IN_STAGE = 25;
  public static ADMISSION_SKIN_WEIGHT_IN_STAGE = 25;
  public static ADMISSION_DIAGNOSIS_WEIGHT_IN_STAGE = 10;

  public static FOLLOWUP_PAIN_WEIGHT_IN_STAGE = 30;
  public static FOLLOWUP_SKIN_WEIGHT_IN_STAGE = 35;
  public static FOLLOWUP_NORTON_WEIGHT_IN_STAGE = 35;

}
